### Health Check
GET http://localhost:3000/ping

### Get Self Client Info
GET http://localhost:3000/api/v1/clients/self
Authorization: JustId 1

### Post new message
POST http://localhost:3000/api/v1/messages
Authorization: JustId 1

{
    "recipient": "+989101448207",
    "text": "Your OTP is: 723895",
    "isExpress": false
}

### Get Reports
GET http://localhost:3000/api/v1/messages/reports?uids=2338963501222985728&uids=2338967296757727232&uids=2338967417721454592
Authorization: JustId 1

### Charge Client Balance Webhook
POST http://localhost:3000/webhook/v1/clients/balance
Authorization: JustId 1

{
    "amount": 12
}